# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tyler Carter
email: tyler@tylercarter.org
description: > # this means to ignore newlines until "baseurl:"
  Developer, building things for the glory of God. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: chacha102
github_username:  chacha

# Build settings
markdown: kramdown
